### ISSUE TITLE
Version different between jaxlib (0.4.12) and jax (0.4.11)

### ISSUE THREAD

**Issue by TeohYx** [ayaka14732/TransCan#4]
The jaxlib is downloaded from https://jax.readthedocs.io/en/latest/developer.html#building-from-source and is in v0.4.12, but the jax is 0.4.11 as in the requirements.txt. This causes error when running pip install -r requirements.txt.

Error:

Traceback (most recent call last):
  File "C:\Users\User\Desktop\Events\DigiLabs\TransCan\generate.py", line 1, in <module>
    import jax
  File "C:\Users\User\Desktop\Events\DigiLabs\TransCan\venv\Lib\site-packages\jax\__init__.py", line 35, in <module>
    from jax import config as _config_module
  File "C:\Users\User\Desktop\Events\DigiLabs\TransCan\venv\Lib\site-packages\jax\config.py", line 17, in <module>
    from jax._src.config import config  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\Events\DigiLabs\TransCan\venv\Lib\site-packages\jax\_src\config.py", line 24, in <module>
    from jax._src import lib
  File "C:\Users\User\Desktop\Events\DigiLabs\TransCan\venv\Lib\site-packages\jax\_src\lib\__init__.py", line 73, in <module>
    version = check_jaxlib_version(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\Events\DigiLabs\TransCan\venv\Lib\site-packages\jax\_src\lib\__init__.py", line 68, in check_jaxlib_version
    raise RuntimeError(msg)
RuntimeError: jaxlib version 0.4.12 is newer than and incompatible with jax version 0.4.11. Please update your jax and/or jaxlib packages.

**Comment by ayaka14732** [comment]
I think jaxlib 0.4.12 has not been published yet?

![](https://github.com/ayaka14732/TransCan/assets/68557794/ef669752-34e9-41fa-bebb-ddb873bca652)
